### ISSUE TITLE
Support for MacOS Arm64 (M1 and M2 series chips)

### ISSUE THREAD

**Issue by xrival** [janestreet/torch#2]
Hi,

I am trying to compile with dune a basic program with a Mac Studio (M1 Pro) using torch/libtorch installed with opam and get errors that seem to point to incorrect support:

`ld: warning: ignoring file /Users/rival/.opam/default/lib/libtorch/lib/libc10.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/rival/.opam/default/lib/libtorch/lib/libtorch_cpu.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/rival/.opam/default/lib/libtorch/lib/libtorch.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
`

This is followed by a very large number of errors of the form "Undefined symbols for architecture arm64", all related to libtorch.

I understand the errors come from the libtorch opam component, but the libtorch page says the development is now moved here.

Can libtorch/torch run on MacOS Arm ? Are they supported for this architecture ? Do we have to take extra steps when installing and using torch on this architecture ? Thanks!

Xavier

**Comment by mwlon** [comment]
This has been mentioned in the previous issue (https://github.com/janestreet/torch/issues/1). TL;DR, the OPAM libtorch package only handles a couple specific use cases, so you'll need to uninstall OCaml torch, set one of several environment variables (e.g. `LIBTORCH=/path/to/libtorch`), and reinstall.

**Comment by vthemelis** [comment]
It looks like your problem is that the native libtorch binaries that you downloaded are for Intel rather than Apple Silicon. You can use these binaries by running an Intel build of OCaml through Rosetta. However, if you want to run natively, read on:

I added more instructions on this in https://github.com/LaurentMazare/ocaml-torch/issues/76#issuecomment-1627318488 but will copy here:

* Download `libtorch` binaries (or build `libtorch` in your Mac). At the moment there are no official pre-build binaries. I downloaded my (unofficial) binaries from https://github.com/mlverse/libtorch-mac-m1/releases .
* Install OCaml >= 4.14 (see here: https://opam.ocaml.org/packages/torch/)
* Double check what `libtorch` version is compatible with the current version of OCaml torch. Version 1.13.1 is the one you want with `v0.16.0` version of OCaml `torch`.
* Set the `LIBTORCH` environment variable to the directory that includes the include and lib directories.

To install with opam:
```
opam install torch.v0.16.0 --ignore-constraints-on libtorch
```
Note that I had to ignore-constraints to avoid failing because `libtorch` (an OCaml/OPAM library that contains pre-build libtorch binaries for some architectures that do not include M1/M2) is disabled for M1 Mac. Note also that I explicitly had to set the version of the package (JaneStreet version starts with v0 rather than 0) as I otherwise resolve to version 0.10 which is way too old.

**Comment by xrival** [comment]
Thanks a lot for the responses. It lets me get further indeed, but still I am not quite there yet.
I installed the libtorch version 1.13.1 from that repository, and torch v0.16.0 through opam with the above command (with OCaml switch 5.0.0).
My OCaml program now compiles, but does not run due to some library signing issue in libtorch.

`dyld[37489]: Library not loaded: @rpath/libc10.dylib
  Referenced from: <2C5EF24E-B74C-38E8-853D-8B9EEB898C06> /Users/me/shared/git/main-git/programming/pyro/minipyro-experiment/ml
  Reason: tried: '/Users/me/installs/libtorch/lib/libc10.dylib' (code signature in <200B70A8-8AC0-3616-AD70-3A55BA91345F> '/Users/me/installs/libtorch/lib/libc10.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/me/installs/libtorch/lib/libc10.dylib' (no such file), '/Users/me/installs/libtorch/lib/libc10.dylib' (code signature in <200B70A8-8AC0-3616-AD70-3A55BA91345F> '/Users/me/installs/libtorch/lib/libc10.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/me/installs/libtorch/lib/libc10.dylib' (no such file), '/usr/local/lib/libc10.dylib' (no such file), '/usr/lib/libc10.dylib' (no such file, not in dyld cache)
Abort trap: 6
`

Of course, all suggestions are appreciated; otherwise I will start an issue on libtorch (I did not do it at first, as I thought that it was not maintained anymore).

**Comment by vthemelis** [comment]
This is just a case of bypassing security measures in your Mac that don't allow you to execute dynamic libraries that you downloaded off the web.

**Comment by xrival** [comment]
Indeed, I found out how it can be resolved (command 'sudo xattr -d com.apple.quarantine' on three files in libtorch).
Thanks a lot @vthemelis, it is working now!

**Comment by mwlon** [comment]
Closing this, since the installation was successful. Thanks @vthemelis
